---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/21 13:45
---

---@class LuaUtils
local LuaUtils = class("LuaUtils")


---isStrNullOrEmpty 字符串是否合法
---@param str string
function LuaUtils.isStrNullOrEmpty(str)
    return str == nil or str == ""
end

function LuaUtils:splitString(delimiter)
    delimiter = delimiter or "|"
    -- 通过分隔符delimiter分割字符串到table
    local result = {}
    for match in (string.gmatch(delimiter, "[^%s]+")) do
        table.insert(result, match)
    end
    return result
end


return LuaUtils