---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/26 10:41
--- 红点Node-表现层
---

---@class RedPointNode
local RedPointNode = class("RedPointNode", function()
    return display.newNode()
end)
---@type RedPointConst
local RedPointConst = require("redPoint.RedPointConst")
---@type RedPointManager
local RedPointManager = app.redPointManager

---@param customData table 自定义红点刷新数据
function RedPointNode:ctor(params)
    self.id = params.id
    self.idString = params.idString or RedPointManager:getIdStringById(self.id)
    self.redPointType = RedPointConst.NONE
    self.showNum = 0
    self.getUIFunc = params.getUIFunc
    self.customData = params.customData
    self:setNodeEventEnabled(true)

    -- view
    self.redPointNode = nil
    self.customRedPointNode = nil
    self.numLabel = nil
end

--- 进入时就应该刷新红点
function RedPointNode:onEnter()
    RedPointManager:bind(self, self.id)
    RedPointManager:forceUpdateRedPoint(self)
end

function RedPointNode:onExit()
    RedPointManager:unbind(self, self.id)
end

---getCustomData 获取自定义数据
function RedPointNode:getCustomData()
    return self.customData
end

function RedPointNode:setBindKey(bindKey)
    self.bindKey = bindKey
end


--- 这个接口用来控制显示与否
function RedPointNode:updateShow(redPointType, showNum)
    if self.showNum == showNum and self.redPointType == redPointType then
        --- 状态相同，不用显示刷新
        return
    end

    self.showNum = showNum
    -- 如果当前显示类型的对应showValue为0，不显示红点
    if (redPointType == self.redPointType and showNum == 0) then     -- 如果为0直接隐藏
        if self.redPointNode then
            self.redPointNode:setVisible(false)
        end
        return
    end

    -- todo: ui刷新逻辑后期补全
    if showNum > 0 then
        if self.redPointType ~= redPointType then
            self.redPointType = redPointType
            if not self.getUIFunc then
                if self.customRedPointNode then
                    self.customRedPointNode:removeFromParent()
                    self.customRedPointNode = nil
                end
                if not self.redPointNode then       -- 创建红点底
                    self.redPointNode = display.newSprite("#pubui_redPoint.png")
                    self.redPointNode:addTo(self)
                end
                if redPointType == RedPointConst.TYPE.NEW then
                    -- self.redPointNode = display.newSprite("redPoint/new.png")
                elseif redPointType == RedPointConst.TYPE.NUMBER then
                    if not self.numLabel then
                        self.numLabel = display.newBMFontLabel({
                            font = 'font/redPoint.fnt',
                        }):addTo(self.redPointNode)
                        self.numLabel:setAdditionalKerning(-10)
                    end 
                    self.numLabel:setString(tostring(showNum))
                    local lblsize = self.numLabel:getContentSize()
                    local redSize = self.redPointNode:getContentSize()
                    self.numLabel:align(display.BOTTOM_CENTER, redSize.width / 2, (redSize.height - lblsize.height) / 2)
                end
                self.redPointNode:setVisible(true)
            else
                if self.redPointNode then
                    self.redPointNode:setVisible(false)
                end
                -- 移除原来的自定义红点
                if self.customRedPointNode then
                    self.customRedPointNode:removeFromParent()
                    self.customRedPointNode = nil
                end

                -- 如果是自定义红点，需要有getUIFunc
                if redPointType == RedPointConst.TYPE.CUSTOM1 then
                    local uiPath = self.getUIFunc()
                    self.customRedPointNode = display.newSprite(uiPath)
                    self.customRedPointNode:addTo(self)
                end
                self.customRedPointNode:setVisible(true)
            end
        end
    end
end

---如果有动画播放动画 todo
function RedPointNode:playRedPointAnim(redPointType)
end

return RedPointNode