---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/21 14:44
---

---@class RedPointConst
local RedPointConst = {}

RedPointConst.TYPE = {
    NONE = 1,           -- 没有红点
    NEW = 2,            -- new红点
    NORMAL = 3,         -- 普通红点
    NUMBER = 4,         -- 数字红点
    CUSTOM1 = 5,        -- 自定义，往后递增
}

--- 红点优先级定义
RedPointConst.PRIORITY = {
    [1] = "NONE",
    [2] = "NEW",
    [3] = "NORMAL",
    [4] = "NUMBER",
    [5] = "CUSTOM1",
}

--- 需要判断所有子红点的红点类型
RedPointConst.FULL_CHECK_TYPE = {
    RedPointConst.TYPE.NUMBER,
}

return RedPointConst