---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/26 10:41
--- 红点Node-表现层
---

---@class RedPointNode
local RedPointNode = class("RedPointNode", function()
    return display.newNode()
end)
---@type RedPointConst
local RedPointConst = require("RedPointConst")
---@type RedPointManager
local RedPointManager = require("RedPointManager")

---@param customData table 自定义红点刷新数据
function RedPointNode:ctor(params, customData)
    self.id = params.id
    self.idString = params.idString
    self.redPointType = RedPointConst.NONE
    self.showNum = 0
    self.redPointNode = nil
    self.getUIFunc = nil
    self.customData = customData
    self.removeTag = false

    --[[
        todo： 减少table.remove的次数
        1. 新增移除标记，一次性移除，而不是每次退出界面移除 ✔
        self.removeTag = false
        2. 增加一个bindKey，很难找到这样的bindKey
        self.bindKey = ""
    ]]
end

--- 进入时就应该刷新红点
function RedPointNode:onLoad()
    --RedPointManager           调用RedPointManager的接口/发送事件
                                -- 采用事件形式的话，需要确认是否需要区分同一刷新事件对应的红点，如何区分
    RedPointManager:bind(self, self.idString)
end

---getCustomData 获取自定义数据
function RedPointNode:getCustomData()
    return self.customData
end

function RedPointNode:setBindKey(bindKey)
    self.bindKey = bindKey
end


--- 这个接口用来控制显示与否
function RedPointNode:updateShow(showNum, redPointType)
    if self.showNum == showNum and self.redPointType == redPointType then
        --- 状态相同，不用显示刷新
        return
    end

    self.showNum = showNum
    if (redPointType == RedPointConst.TYPE.NONE or showNum == 0) and self.redPointNode then
        self.redPointNode:setVisible(false)
        return
    end

    -- todo: ui刷新逻辑后期补全
    if showNum > 0 then
        if self.redPointType ~= redPointType then
            --self.redPointNode:setSpriteFrame()
            --- 显示类型不同，则需要刷新
            self.redPointType = redPointType
            self:removeAllChildren()

            if redPointType == RedPointConst.TYPE.NEW then
                self.redPointNode = display.newSprite("redPoint/new.png")
            elseif redPointType == RedPointConst.TYPE.NORMAL then
                self.redPointNode = display.newSprite("redPoint/normal.png")
            elseif redPointType == RedPointConst.TYPE.NUMBER then
                self.redPointNode = display.newSprite("redPoint/number.png")
            else
                --- 自定义红点走自己的逻辑
                local path = self.getUIFunc()
            end
            if self.redPointNode then
                self:addChild(self.redPointNode)
            end
        end
    end
end

function RedPointNode:setRemove()
    self.removeTag = true
end



return RedPointNode