---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/26 10:41
--- 红点Node-表现层
---

---@class RedPointNode
local RedPointNode = class("RedPointNode", function()
    return display.newNode()
end)
---@type RedPointConst
local RedPointConst = require("redPoint.RedPointConst")
---@type RedPointManager
local RedPointManager = app.redPointManager

---@param customData table 自定义红点刷新数据
function RedPointNode:ctor(params)
    self.id = params.id
    self.idString = params.idString or RedPointManager:getIdStringById(self.id)
    self.redPointType = RedPointConst.TYPE.NONE      -- 由关联的逻辑红点决定
    -- {showType -> {logicType}}
    self.checkMap = params.checkMap         -- 用于一个显示类型可以对应多个显示逻辑，有一个红点满足条件则显示

    self.showNum = 0
    self.getUIFunc = params.getUIFunc
    self.customData = params.customData
    self.checkRefreshFunc = params.checkRefreshFunc     -- 用来判断是否是同一个红点
    self:setNodeEventEnabled(true)

    -- view
    self.redPointNode = nil
    self.customRedPointNode = nil
    self.numLabel = nil
end

--- 进入时就应该刷新红点
function RedPointNode:onEnter()
    RedPointManager:bind(self, self.id)
    RedPointManager:forceUpdateRedPoint(self)
end

function RedPointNode:onExit()
    RedPointManager:unbind(self, self.id)
end

---getCustomData 获取自定义数据
function RedPointNode:getCustomData()
    return self.customData
end

function RedPointNode:getCheckMap()
    return self.checkMap
end

--- 这个接口用来控制显示与否
--- todo： 需要修改，红点的显示类型应该由两种情况决定：1.子红点 2.强制为某种红点
function RedPointNode:updateShow(redPointType, showNum)
    if redPointType == RedPointConst.TYPE.NONE then     -- 没有红点显示类型
        if self.redPointNode then
            self.redPointNode:setVisible(false)
        end
        if self.customRedPointNode then
            self.customRedPointNode:setVisible(false)
        end
    end

    if self.showNum == showNum and self.redPointType == redPointType then
        --- 状态相同，不用显示刷新
        return
    end

    self.showNum = showNum
    -- 如果当前显示类型的对应showValue为0，不显示红点
    if (redPointType == self.redPointType and showNum == 0) then     -- 如果为0直接隐藏
        if self.redPointNode then
            self.redPointNode:setVisible(false)
        end
        return
    end

    -- todo: ui刷新逻辑后期补全
    if showNum > 0 then
        if self.redPointType ~= redPointType then
            self.redPointType = redPointType
            if not self.getUIFunc then
                if self.customRedPointNode then
                    self.customRedPointNode:removeFromParent()
                    self.customRedPointNode = nil
                end
                if not self.redPointNode then       -- 创建红点底
                    self.redPointNode = display.newSprite("#pubui_redPoint.png")
                    self.redPointNode:addTo(self)
                end
                if redPointType == RedPointConst.TYPE.NEW then
                    if not self.numLabel then
                        self.numLabel = display.newBMFontLabel({
                            font = 'font/redPoint.fnt',
                        }):addTo(self.redPointNode)
                        self.numLabel:setAdditionalKerning(-10)
                    end 
                    self.numLabel:setString('新')
                    local lblsize = self.numLabel:getContentSize()
                    local redSize = self.redPointNode:getContentSize()
                    self.numLabel:align(display.BOTTOM_CENTER, redSize.width / 2, (redSize.height - lblsize.height) / 2)
                elseif redPointType == RedPointConst.TYPE.NUMBER then
                    if not self.numLabel then
                        self.numLabel = display.newBMFontLabel({
                            font = 'font/redPoint.fnt',
                        }):addTo(self.redPointNode)
                        self.numLabel:setAdditionalKerning(-10)
                    end 
                    self.numLabel:setString(tostring(showNum))
                    local lblsize = self.numLabel:getContentSize()
                    local redSize = self.redPointNode:getContentSize()
                    self.numLabel:align(display.BOTTOM_CENTER, redSize.width / 2, (redSize.height - lblsize.height) / 2)
                end
                self.redPointNode:setVisible(true)
            else
                if self.redPointNode then
                    self.redPointNode:setVisible(false)
                end
                -- 移除原来的自定义红点
                if self.customRedPointNode then
                    self.customRedPointNode:removeFromParent()
                    self.customRedPointNode = nil
                end

                -- 如果是自定义红点，需要有getUIFunc
                if redPointType == RedPointConst.TYPE.CUSTOM1 then
                    local uiPath = self.getUIFunc()
                    self.customRedPointNode = display.newSprite(uiPath)
                    self.customRedPointNode:addTo(self)
                end
                self.customRedPointNode:setVisible(true)
            end
        elseif redPointType == RedPointConst.TYPE.NUMBER then       -- 数字红点只要数字变化了就要刷新
            self.numLabel:setString(tostring(showNum))
        end
    end
end

-- 判断是否需要更新当前红点的显示，用来避免重复计算(通过customData来判断)
-- 主要用来解决同一个逻辑红点对应多个ui节点的情况
function RedPointNode:checkRequireRefresh(eventData)
    if self.checkRefreshFunc then
        return self.checkRefreshFunc(eventData, self.customData)
    end
    return true
end



---如果有动画播放动画 todo
function RedPointNode:playRedPointAnim(redPointType)
end

return RedPointNode