---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/21 14:44
---

---@class RedPointConst
local RedPointConst = {}

RedPointConst.TYPE = {
    NONE = 0,           -- 没有红点
    NEW = 1,            -- new红点
    NORMAL = 2,         -- 普通红点
    NUMBER = 3,         -- 数字红点
    CUSTOM1 = 4,        -- 自定义，往后递增
}

--- 红点优先级定义
RedPointConst.PRIORITY = {
    [1] = "NONE",
    [2] = "NEW",
    [3] = "NORMAL",
    [4] = "NUMBER",
    [5] = "CUSTOM1",
}

return RedPointConst