---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/26 10:41
--- 红点UI
---

---@class UIRedPointNode
local UIRedPointNode = class("UIRedPointNode", function()
    return display.newNode()
end)
---@type RedPointConst
local RedPointConst = require("RedPointConst")

function UIRedPointNode:ctor()
    self.id = 0
    self.idString = ""
    self.redPointNode = nil
    self.redPointType = RedPointConst.NONE
    self.showNum = 0
end

function UIRedPointNode:updateShow(showNum, redPointType)
    if self.showNum == showNum and self.redPointType == redPointType then
        --- 状态相同，不用显示刷新
        return
    end

    self.showNum = showNum
    if (redPointType == RedPointConst.TYPE.NONE or showNum == 0) and self.redPointNode then
        self.redPointNode:setVisible(false)
        return
    end

    -- todo: ui刷新逻辑后期补全
    if showNum > 0 then
        if self.redPointType ~= redPointType then
            --- 显示类型不同，则需要刷新
            self.redPointType = redPointType
            self:removeAllChildren()
            if redPointType == RedPointConst.TYPE.NEW then
                self.redPointNode = display.newSprite("redPoint/new.png")
            elseif redPointType == RedPointConst.TYPE.NORMAL then
                self.redPointNode = display.newSprite("redPoint/normal.png")
            elseif redPointType == RedPointConst.TYPE.NUMBER then
                self.redPointNode = display.newSprite("redPoint/number.png")
            end
            if self.redPointNode then
                self:addChild(self.redPointNode)
            end
        end
    end
end



return UIRedPointNode