---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/5/26 10:41
--- 红点UI
---

---@class UIRedPointNode
local UIRedPointNode = class("UIRedPointNode", function()
    return display.newNode()
end)
---@type RedPointConst
local RedPointConst = require("RedPointConst")

function UIRedPointNode:ctor()
    self.id = 0
    self.idString = ""
    self.redPointNode = nil
    self.redPointType = RedPointConst.NONE
    self.isShow = false
end

function UIRedPointNode:setShow(isShow, redPointType)
    if self.isShow == isShow and self.redPointType == redPointType then
        return
    end
    if self.redPointType == RedPointConst.TYPE.NONE then
        self.isShow = false

        return
    end

    if self.redPointType ~= redPointType then
        self.redPointType = redPointType
        self:removeAllChildren()
        local redPointNode = nil
        if redPointType == RedPointConst.TYPE.NEW then
            self.redPointNode = display.newSprite("redPoint/new.png")
        elseif redPointType == RedPointConst.TYPE.NORMAL then
            self.redPointNode = display.newSprite("redPoint/normal.png")
        elseif redPointType == RedPointConst.TYPE.NUMBER then
            self.redPointNode = display.newSprite("redPoint/number.png")
        end
        if self.redPointNode then
            self:addChild(self.redPointNode)
        end
    end

end



return UIRedPointNode