---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujunfei.
--- DateTime: 2025/7/15 11:07
---

local RedPointConst = {}
RedPointConst.SHOW_TYPE = {
    NONE = 0,       -- 可作为逻辑红点
    DEFAULT = 1,
    NUMBER = 2,
    NEW = 3,

}

return RedPointConst